-- Down migration for abac_schema
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS user_attributes CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS policies CASCADE;
DROP TABLE IF EXISTS permissions CASCADE;
DROP TABLE IF EXISTS resources CASCADE;
DROP TABLE IF EXISTS attributes CASCADE;
DROP FUNCTION IF EXISTS update_updated_at_column CASCADE;
